# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build-patch --if-present
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Updated version" -a
        
    - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with:
        path: "package.json"
        prop_path: "version"
        
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ format('{0}_{1}', 'reactBuild', steps.version.outputs.prop) }}
        path: build
